services:
  db:
    volumes:
      - ./:/app

  api:
    command:
      [
        "uvicorn",
        "lan_app.api:app",
        "--host",
        "0.0.0.0",
        "--port",
        "7860",
        "--reload",
        "--reload-dir",
        "/app/lan_app",
        "--reload-dir",
        "/app/lan_transcriber",
      ]
    volumes:
      - ./:/app

  worker:
    volumes:
      - ./:/app
